config/routes.rb
MonServ::Application.routes.draw do
  resource :stats do
    collection do
      get 'ping'
      get 'all'
    end
  end

  resources :nodes do
    resources :stats
    collection do
      post 'add_macs'
    end
  end
  
  match 'nodes/:node_id/stats/:type/:name' => 'stats#show'

end

app/models/node.rb
require 'netaddr'

class Node < ActiveRecord::Base
  attr_accessible :alert_addresses, :ip_address
  after_save :update_collectd
  
  def id_hex 
    "%012x" % self.id
  end
  
  def update_collectd
    conf = Collectd.new
    conf.set_ping_hosts(Node.all.map(&:link_local_address))
    # Set mac-Adresses
    macs_by_ll = {}
    
    Node.all.each do |node|
      macs_by_ll[node.link_local_address] = NetAddr::EUI48.new(node.id).address(:Delimiter => ':')
    end
    conf.write_mac_list macs_by_ll
    
  end
  
  def link_local_address
    NetAddr::EUI48.new(self.id).link_local
  end

  def to_collectd_node
    CollectdNode.new(self.id_hex,self.link_local_address)
  end

end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
  # users.password_hash in the database is a :string
  include BCrypt

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
      @password = Password.create(new_password)
      self.password_hash = @password
  end
  
  def self.authenticate(login,password)
    u = User.find_by_login(login)
    return u.password == password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_headers

  def set_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Expose-Headers'] = 'ETag'
    headers['Access-Control-Allow-Methods'] = 'GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD'
    headers['Access-Control-Allow-Headers'] = '*,x-requested-with,Content-Type,If-Modified-Since,If-None-Match'
    headers['Access-Control-Max-Age'] = '86400'
  end

  private
  def auth
    authenticate_or_request_with_http_basic do |username, password|
      User.authenticate(username,password)
     end
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_filter :auth, :only => [:create, :update,:delete]
  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all
    @rtt = {}
    @loss = {}
    conf = Collectd.new
    @nodes.each do |node|
      collectd_node = CollectdNode.new(node.id.to_s(16),node.link_local_address)
      begin
        @rtt[node] = conf.stat(collectd_node,"ping",nil,nil).rtt_5_min
        @loss[node] = conf.stat(collectd_node,"ping",nil,nil).loss_5_min
      rescue Exception => e #Ignore errors in single hosts (-> missing rrd-Files for newly created ...)
        logger.error "Unable to calculate stats: #{e}"
      end
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json do 
        data = {}
        @nodes.each do |n| 
          data[n.id] = {id_hex: n.id_hex, 
            loss_5_min: (@loss[n].nil? || @loss[n].nan?) ? nil : @loss[n], 
            rtt_5_min: (@loss[n].nil? || @rtt[n].nan?) ? nil : @rtt[n]}
        end
        render json: data
      end
    end
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
    @node = Node.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @node }
    end
  end

  # GET /nodes/new
  # GET /nodes/new.json
  def new
    @node = Node.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @node }
    end
  end

  # GET /nodes/1/edit
  def edit
    @node = Node.find(params[:id])
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(params[:node])
    @node.id = params[:node][:id]
    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render json: @node, status: :created, location: @node }
      else
        format.html { render action: "new" }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nodes/1
  # PUT /nodes/1.json
  def update
    @node = Node.find(params[:id])

    respond_to do |format|
      if @node.update_attributes(params[:node])
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node = Node.find(params[:id])
    @node.destroy

    respond_to do |format|
      format.html { redirect_to nodes_url }
      format.json { head :no_content }
    end
  end
  
  ## Add macs, if not existing
  def add_macs
     macs = params[:mac]
     if macs.is_a?(String)
      macs = [macs]
     end
     macs.each do |mac_str|
     mac = mac_str.to_i(16)
     unless Node.find_by_id(mac)
       n = Node.new
       n.id = mac
       begin
         n.save!
       rescue Exception => e
         logger.error "Node #{mac} / #{mac_str} cannot be added #{e}"
       end
     end
   end
   render json: "ok", status: :created
 end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  
  def ping
    start_t = (params[:start] || -60).to_i
    interval = (params[:interval] || 10).to_i
    end_t = ((params[:end] || Time.now).to_i / interval) * interval

    conf = Collectd.new
    data = {}
    node_scope = Node.scoped
    if node_id = params[:node_id]
      node_scope = node_scope.where(id: node_id)
    end

    node_scope.each do |node|
      collectd_node = node.to_collectd_node
      stat = conf.stat(collectd_node,"ping",nil,nil)
      begin 
        result = stat.all_stats(start_t,end_t,interval)
        index = 1 # Not 0! -> = 0 will introduce off by one error, since starting at f_start means, the that first value is available at start+interval
        data[node.id] = []
        result[:step].each do |res|
          current = result[:fstart].to_i + (index * interval)
          data[node.id] << [current,(res.first.nan?) ? nil : res.first]
          index += 1
        end if result[:step]
      rescue Exception => e
        logger.warn "Data for #{node.id} is missing - #{e}"
      end
    end
    respond_to do |format|
      format.json {render json: daat.to_json}
    end
  end
  
  def all
    conf = Collectd.new
    result = {}
    Node.all.each do |n|
      result[n.id_hex] = {
        ping: {},
        stations: {}
      }
      begin
        result[n.id_hex][:ping] = conf.stat(n.to_collectd_node,'ping',nil,nil).summary 
      rescue Exception => e
        logger.warn "Unable to build ping statistics for #{n.inspect}: #{e.inspect}"
      end

      IwinfoStat.interfaces(n.to_collectd_node).each do |iface|
        begin
          result[n.id_hex][:stations][iface] = conf.stat(n.to_collectd_node,'iwinfo',nil,{'iface' => iface}).summary
        rescue Exception => e
          logger.warn "Unable to build iwinfo statistics for #{n.inspect}: #{e.inspect}"
        end
      end
    end
    render json: result.to_json
  end
  
  
  def show
    conf = Collectd.new
    @node = Node.find(params[:node_id])
    secs = (params[:secs] || 3600).to_i
    name = params[:name]
    type = params[:type]
    id = params[:id] || params[:type]
    width = params[:width] || 600
    height = params[:height] || 200
    no_summary = params[:no_summary]
    @stat_params = params[:stat]
    cn = @node.to_collectd_node
    respond_to do |format|
      format.png do 
        stat = conf.stat(cn,id,name,@stat_params)
        send_data stat.create_graph(width,height,secs,no_summary), :type => 'image/png',:disposition => 'inline'
      end
      # try building stat object - may not succeed - to few parameters atm ...
      format.html do 
        begin
          @stat = conf.stat(cn,id,name,@stat_params)
        rescue Exception => e
          logger.info "Unable to construct stat object for debugging purpose #{e.inspect} - don't panic"
        end
        render action: id 
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MonServ</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/nodes/_form.html.erb
<%= form_for(@node) do |f| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% if f.object.id.blank?%>
<div class="field">
  <%= f.label :id %><br />
  <%= f.text_field :id %>
</div>

<% end %>

  <div class="field">
    <%= f.label :ip_address %><br />
    <%= f.text_field :ip_address %>
  </div>
  <div class="field">
    <%= f.label :alert_addresses %><br />
    <%= f.text_area :alert_addresses %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<h1>Listing nodes</h1>

<table>
  <tr>
	<th>ID</th>
	<th>Node-ID</th>
	<th>RTT</th>
	<th>Loss</th>
	<th>Iwinfo-Interfacey</th>
    <th></th>
  </tr>

<% @nodes.each do |node| %>
  <tr>
	<td><%= node.id%></td>
	<td><%= node.id_hex%></td>
	<td><%= @rtt[node].inspect%></td>
	<td><%= @loss[node].inspect%></td>
	<td>
		<% for iface in IwinfoStat.interfaces(node.to_collectd_node) %>
			<%= link_to iface, node_stat_path(node,'iwinfo', {'stat[iface]' => iface}) %>
			<%#= iface %>
		<% end %> 

	</td>
	<td>
		<%= link_to 'Ping', node_stat_path(node,'ping')%>
		<%= link_to 'RX / TX', node_stat_path(node,'rxtx')%>
		<%= link_to 'Errors', node_stat_path(node,'errors')%>

	</td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Node', new_node_path %>

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Node-ID</b>
  <%= @node.id_hex %>
</p>

<p>
  <b>5 Minutes</b><br />
	<img src="/nodes/<%= @node.id %>/stats/ping.png?secs=300&width=600&height=200" />
</p>

<p>
  <b>1 Hour</b><br />
	<img src="/nodes/<%= @node.id %>/stats/ping.png?secs=3600&width=600&height=200" />
</p>

<p>
  <b>1 Day</b>
  <% secs_day = 24 * 3600 %><br />
	<img src="/nodes/<%= @node.id %>/stats/ping.png?secs=<%= secs_day %>&width=600&height=200" />
</p>

<p>
  <% secs_week = 7 * 24 * 3600 %>
  <b>1 Week</b><br />
	<img src="/nodes/<%= @node.id %>/stats/ping.png?secs=<%= secs_week %>&width=600&height=200" />
</p>



<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>

app/views/stats/errors.html.erb
<p>
  <b>Node-ID</b>
  <%= @node.id.to_s(16) %>
</p>
<%
	defs = {
		"5 Minutes" => 600,
		"1 Hour " => 3600,
		"1 Day" => 24 * 3600,
		"1 Week" => 7 * 24 * 3600,
		"1 Year" => 365 * 24 * 3600
	}
%>

<% for if_name in ['br-wan','wlan0-1'] do%>
<h2><%= if_name%></h2>
<% defs.each_pair do |name,interval| %>
<p>
  <b><%= name %></b><br />
	<img src="/nodes/<%= @node.id %>/stats/error/<%=if_name%>.png?secs=<%=interval%>&width=400&height=150" />
	<img src="/nodes/<%= @node.id %>/stats/error/<%=if_name%>.png?secs=<%=interval%>&width=400&height=150" />

</p>

<% end %>
<% end %>

app/views/stats/index.html.erb
<ul>
	<% for stat in @stats %>
	<li><a href="stats/<%=stat.plugin%>/<%=stat.name%>.rrd"><%=stat.plugin%>/<%=stat.name%>.rrd</a></li>
	<% end %>

</ul>
	

app/views/stats/interface.html.erb
<p>
  <b>Node-ID</b>
  <%= @node.id.to_s(16) %>
</p>
<%
	defs = {
		"5 Minutes" => 600,
		"1 Hour " => 3600,
		"1 Day" => 24 * 3600,
		"1 Week" => 7 * 24 * 3600,
		"1 Year" => 365 * 24 * 3600
	}
%>

<% defs.each_pair do |name,interval| %>
<p>
  <b><%= name %></b><br />
	<img src="/nodes/<%= @node.id %>/stats/interface.png?secs=<%=interval%>&width=600&height=200" />
</p>

<% end %>

app/views/stats/iwinfo.html.erb
<p>
  <b>Node-ID</b>
  <%= @node.id.to_s(16) %><br />
  Stations now: <%= @stat.stations_now %><br />
  Stations 1 day (avg): <%= @stat.stations_1d %> <br />
  Stations 30 day (avg): <%= @stat.stations_30d %> <br />


</p>
<%
	defs = {
		"5 Minutes" => 600,
		"1 Hour " => 3600,
		"1 Day" => 24 * 3600,
		"1 Week" => 7 * 24 * 3600,
		"1 Year" => 365 * 24 * 3600
	}
%>


<% defs.each_pair do |name,interval| %>
<p>
  <b><%= name %></b><br />
	<img src="/nodes/<%= @node.id %>/stats/iwinfo.png?secs=<%=interval%>&width=600&height=200&stat[iface]=<%= @stat_params['iface'] %>" />
</p>

<% end %>

app/views/stats/ping.html.erb
<p>
  <b>Node-ID</b>
  <%= @node.id.to_s(16) %>
</p>
<%
	defs = {
		"5 Minutes" => 600,
		"1 Hour " => 3600,
		"1 Day" => 24 * 3600,
		"1 Week" => 7 * 24 * 3600,
		"1 Year" => 365 * 24 * 3600
	}
%>

<% defs.each_pair do |name,interval| %>
<p>
  <b><%= name %></b><br />
	<img src="/nodes/<%= @node.id %>/stats/ping.png?secs=<%=interval%>&width=600&height=200" />
</p>

<% end %>

app/views/stats/rxtx.html.erb
<p>
  <b>Node-ID</b>
  <%= @node.id.to_s(16) %>
</p>
<%
	defs = {
		"5 Minutes" => 600,
		"1 Hour " => 3600,
		"1 Day" => 24 * 3600,
		"1 Week" => 7 * 24 * 3600,
		"1 Year" => 365 * 24 * 3600
	}
%>

<% for if_name in ['br-wan','wlan0-1'] do%>
<h2><%= if_name%></h2>
<% defs.each_pair do |name,interval| %>
<p>
  <b><%= name %></b><br />
	<img src="/nodes/<%= @node.id %>/stats/interface/octets-<%=if_name%>.png?secs=<%=interval%>&width=400&height=150" />
	<img src="/nodes/<%= @node.id %>/stats/interface/packets-<%=if_name%>.png?secs=<%=interval%>&width=400&height=150" />

</p>

<% end %>
<% end %>